# Bridges all Gazebo transport topics you listed into ROS2 topics
# Direction: Gazebo -> ROS2

- topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS

- topic_name: /gazebo/resource_paths
  ros_type_name: ros_gz_interfaces/msg/StringMsg
  gz_type_name: gz.msgs.StringMsg
  direction: GZ_TO_ROS

- topic_name: /stats
  ros_type_name: ros_gz_interfaces/msg/WorldStatistics
  gz_type_name: gz.msgs.WorldStatistics
  direction: GZ_TO_ROS

- topic_name: /world/default/clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS

- topic_name: /world/default/dynamic_pose/info
  ros_type_name: ros_gz_interfaces/msg/EntityDynamicPose
  gz_type_name: gz.msgs.Pose_V
  direction: GZ_TO_ROS

- topic_name: /world/default/pose/info
  ros_type_name: ros_gz_interfaces/msg/EntityPose
  gz_type_name: gz.msgs.Pose_V
  direction: GZ_TO_ROS

- topic_name: /world/default/scene/deletion
  ros_type_name: ros_gz_interfaces/msg/EntityDelete
  gz_type_name: gz.msgs.Boolean
  direction: GZ_TO_ROS

- topic_name: /world/default/scene/info
  ros_type_name: ros_gz_interfaces/msg/Entity
  gz_type_name: gz.msgs.Entity
  direction: GZ_TO_ROS

- topic_name: /world/default/state
  ros_type_name: sensor_msgs/msg/JointState
  gz_type_name: gz.msgs.Model
  direction: GZ_TO_ROS

- topic_name: /world/default/stats
  ros_type_name: ros_gz_interfaces/msg/WorldStatistics
  gz_type_name: gz.msgs.WorldStatistics
  direction: GZ_TO_ROS

- topic_name: /world/shapes/clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS

- topic_name: /world/shapes/dynamic_pose/info
  ros_type_name: ros_gz_interfaces/msg/EntityDynamicPose
  gz_type_name: gz.msgs.Pose_V
  direction: GZ_TO_ROS

- topic_name: /world/shapes/pose/info
  ros_type_name: ros_gz_interfaces/msg/EntityPose
  gz_type_name: gz.msgs.Pose_V
  direction: GZ_TO_ROS

- topic_name: /world/shapes/scene/deletion
  ros_type_name: ros_gz_interfaces/msg/EntityDelete
  gz_type_name: gz.msgs.Boolean
  direction: GZ_TO_ROS

- topic_name: /world/shapes/scene/info
  ros_type_name: ros_gz_interfaces/msg/Entity
  gz_type_name: gz.msgs.Entity
  direction: GZ_TO_ROS

- topic_name: /world/shapes/state
  ros_type_name: sensor_msgs/msg/JointState
  gz_type_name: gz.msgs.Model
  direction: GZ_TO_ROS

- topic_name: /world/shapes/stats
  ros_type_name: ros_gz_interfaces/msg/WorldStatistics
  gz_type_name: gz.msgs.WorldStatistics
  direction: GZ_TO_ROS

